language: node_js
node_js:
  - node
before_install:
  - npm install -g @angular/cli
install:
  - npm install
script:
  - ng test build --prod
branches:
  only:
    - master
deploy:
  provider: heroku
  api_key:
    secure: $API_TOKEN
  app: gardening
