sudo: required
dist: trusty
language: node_js
node_js:
  - node
addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta
before_install:
  - npm install -g @angular/cli
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install: npm install
branches:
  only:
    - master
script:
  ng test --watch=false
after_script:
- chmod +x publish-gh-pages.sh && ./publish-gh-pages.sh
deploy:
  provider: heroku
  api_key:
    secure: GJo7M1JdQtCmTzdfO0az40Z3qEZp/89Mv+rpZwCrT4rDwkLSr472dCkNO9QwgaHxC7AOPTq7z22s1vGSInkglbdnyNgfMFvfzkaXu0tFRm64xFk8IMPM/ejZdZ/+4xLeELRW8+WAd6U7GugXPxIvuIQMVopASAzC2wDQj6BBklKlW0eIXHeDeL3JQU5nMrLX8WycQvUzGcFzhuB6CFWEbzwIusvZNx0oEsBysdjK7VHpgM44o+312FF10B1AUttLgJ8JgDZYqU/I/qcNZPpMB/2HEiTtPPjmYkgo3AOdzyDFuULngCuAFzFApsjKf5CtLymUlfqaMWJMp1mytCdK+Dmn6fUpt20rohz9a/K9IQlkHmW3EiKFGuSxKdRxLkE6njH1p7gJ0A7aECfdROMltM83sjR+dstWbKhh4Of42+cVJukzCeIAGMoifZZai1KS2vU/zcMm3X1OWRdRw9HFpM5vgrbOr5FvDrmX7eOjDJP1/uYvFZDXtrTbRpXB3TAn2yc3bJyeZ/scoMBtSgFGR1nYAUTUHfRMiGOOZdgO/oFmTDFaGa4lhjjTtmStVUKK3hCvQHlJZq8lB2WkiF15ROE7ZmrXnz4O0PJAAA0DlMPm9kzYf8lMqXdvOmhNeFQsHgRdGcoNZJwYh0XCipwdkcJhFfZfemuKq2f1tRRVUFo=
  app: fuchsbau
  on:
    repo: olmaga/Gardening
